alter table public.watch_specs
  add column if not exists has_chronograph boolean,
  add column if not exists has_gmt boolean;

create or replace view public.watch_comparison_view as
select
  w.id as watch_id,
  w.slug,
  b.id as brand_id,
  b.name as brand_name,
  b.slug as brand_slug,
  c.id as collection_id,
  c.name as collection_name,
  c.slug as collection_slug,
  w.model_name,
  w.reference_number,
  w.nickname,
  w.category,
  w.release_year,
  w.limited_edition,
  w.limited_quantity,
  w.discontinued,
  w.msrp,
  w.currency,
  w.availability_status,
  w.primary_image_url,
  w.source_url,
  w.affiliate_url,
  w.affiliate_partner,
  w.is_featured,
  w.search_keywords,
  w.review_status,
  w.confidence_score,
  ws.case_material,
  ws.case_size_mm,
  ws.case_thickness_mm,
  ws.lug_to_lug_mm,
  ws.lug_width_mm,
  ws.case_finish,
  ws.case_shape,
  ws.weight_grams,
  ws.water_resistance_m,
  ws.water_resistance_bar,
  ws.crown_type,
  ws.crown_guards,
  ws.pushers,
  ws.helium_escape_valve,
  ws.caseback_type,
  ws.caseback_description,
  ws.bezel_type,
  ws.bezel_material,
  ws.bezel_insert_material,
  ws.bezel_color,
  ws.bezel_action,
  ws.crystal_type,
  ws.crystal_shape,
  ws.crystal_coating,
  ws.dial_color,
  ws.dial_texture,
  ws.dial_finish_normalized,
  ws.dial_finish_raw,
  ws.indices_type,
  ws.hand_style,
  ws.lume_type,
  ws.lume_color,
  ws.date_display,
  ws.day_display,
  ws.running_seconds,
  ws.movement_type,
  ws.caliber,
  ws.in_house,
  ws.jewels,
  ws.frequency_hz,
  ws.frequency_vph,
  ws.power_reserve_hours,
  ws.accuracy_claim,
  ws.cosc_certified,
  ws.metas_certified,
  ws.escapement_notes,
  ws.complications,
  ws.rotor_type,
  ws.magnetic_resistance_gauss,
  ws.bracelet_included,
  ws.bracelet_type,
  ws.bracelet_material,
  ws.bracelet_reference_number,
  ws.bracelet_finish_normalized,
  ws.bracelet_finish_raw,
  ws.bracelet_taper_from_mm,
  ws.bracelet_taper_to_mm,
  ws.link_design_normalized,
  ws.link_design_raw,
  ws.end_link_type,
  ws.quick_release,
  ws.clasp_type,
  ws.clasp_finish_normalized,
  ws.clasp_finish_raw,
  ws.clasp_reference_code,
  ws.micro_adjustment_mm,
  ws.micro_adjustment_positions,
  ws.adjustment_system_normalized,
  ws.adjustment_system_raw,
  ws.tool_free_adjustment,
  ws.wears_true_small_large,
  ws.comfort_notes,
  ws.thickness_profile,
  ws.bracelet_comfort_notes,
  ws.clasp_comfort_notes,
  ws.overall_wearability_summary,
  ws.ai_summary,
  ws.spec_completeness_score,
  w.created_at,
  w.updated_at,
  ws.has_chronograph,
  ws.has_gmt
from public.watches w
left join public.brands b on b.id = w.brand_id
left join public.collections c on c.id = w.collection_id
left join public.watch_specs ws on ws.watch_id = w.id;
